language: generic
os: linux
dist: xenial
jobs:
  include:
    - language: python
      name: backend
      python: 3.8
      before_install:
        - cd backend
      install:
        - pip install poetry
        - poetry install
      script:
        - poetry run pytest -s ./tests
    - language: node_js
      name: frontend
      node_js: node
      before-install:
        - cd frontend
      cache:
        directories:
          - node_modules
        timeout: 3
      script:
        - yarn install
        - yarn test
        - yarn run build
    - stage: dockerhub-deploy
      if: branch = master
      script:
        - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        - docker build -f ./nginx/Dockerfile.prod -t codeactor/braingamexyz_nginx:latest ./nginx
        - docker build -f ./backend/Dockerfile.prod -t codeactor/braingamexyz_backend:latest ./backend
        - docker build -f ./frontend/Dockerfile.prod -t codeactor/braingamexyz_frontend:latest ./frontend
        - docker push codeactor/braingamexyz_nginx
        - docker push codeactor/braingamexyz_backend
        - docker push codeactor/braingamexyz_frontend
