language: generic
os: linux
dist: xenial
jobs:
  include:
    - language: python
      name: server
      python: 3.8
      before_install:
        - cd backend
      install:
        - pip install poetry
        - poetry install
      script:
        - poetry run pytest -s ./tests
    - language: node_js
      name: client
      node_js: node
      cache:
        directories:
          - node_modules
        timeout: 3
      script:
        - yarn install
        - yarn test
        - yarn run build
