FROM python:3.8

COPY . /app

WORKDIR /app

RUN pip --no-cache-dir install poetry poetry-setup \
    && poetry config virtualenvs.create false \
    && poetry install \
    && pip uninstall poetry -y \
    && rm -rf ~/.config/pypoetry

EXPOSE 5000

WORKDIR /app/brain-game-backend

CMD ["python", "app_prod.py"]
